# Generated by Django 4.0.3 on 2022-03-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name_plural': 'tickets statuses'},
        ),
    ]
