# Generated by Django 4.0.3 on 2022-03-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_statuses', to='core.ticketstatus'),
        ),
    ]
