# Generated by Django 4.0.3 on 2022-03-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='comments',
            new_name='comment',
        ),
    ]
